apiVersion: apps/v1
kind: Deployment
metadata:
 name: hello-world-node
 namespace: default
 labels:
   app: hello-world-node
   version: "462cb94ef706636ae1549e956b021f05780f4b21"
spec:
 strategy:
   type: RollingUpdate
   rollingUpdate:
     maxSurge: 1
     maxUnavailable: 0
 selector:
   matchLabels:
     app: hello-world-node
 template:
   metadata:
     labels:
       app: hello-world-node
       version: "462cb94ef706636ae1549e956b021f05780f4b21"
   spec:
     affinity:
       podAntiAffinity:
         requiredDuringSchedulingIgnoredDuringExecution:
         - labelSelector:
             matchExpressions:
             - key: app
               operator: In
               values:
               - hello-world-node
           topologyKey: topology.kubernetes.io/zone
         preferredDuringSchedulingIgnoredDuringExecution:
         - weight: 100
           podAffinityTerm:
             labelSelector:
               matchExpressions:
               - key: app
                 operator: In
                 values:
                 - hello-world-node
             topologyKey: kubernetes.io/hostname
     containers:
     - name: hello-world-node
       image: 
       ports:
       - containerPort: 3000
         name: http
       resources:
         requests:
           memory: "128Mi"
           cpu: "100m"
         limits:
           memory: "256Mi"
           cpu: "200m"
       livenessProbe:
         httpGet:
           path: /health
           port: 3000
         initialDelaySeconds: 15
         periodSeconds: 20
         timeoutSeconds: 5
         failureThreshold: 3
       readinessProbe:
         httpGet:
           path: /ready
           port: 3000
         initialDelaySeconds: 5
         periodSeconds: 10
         timeoutSeconds: 3
         failureThreshold: 3
       env:
       - name: NODE_ENV
         value: "production"
       - name: PORT
         value: "3000"
     restartPolicy: Always
     terminationGracePeriodSeconds: 30