apiVersion: v2
name: hello-world-node
description: A Helm chart for Hello World Node.js application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - nodejs
  - web
  - api
maintainers:
  - name: Omer Harush