name: CI/CD Pipeline - Hello World Node.js

on:
  push:
    branches: [ main ]
    paths:
      - 'app/**'
      - 'k8s/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'app/**'
      - 'k8s/**'
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: omer/hello-world-node

jobs:
  # Change detection
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      app: ${{ steps.filter.outputs.app }}
      k8s: ${{ steps.filter.outputs.k8s }}
    steps:
      - uses: actions/checkout@v4
      - name: Detect changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            app:
              - 'app/**'
            k8s:
              - 'k8s/**'

  # Security and quality checks for PRs and main
  security-and-tests:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.app == 'true'
    steps:
      - uses: actions/checkout@v4

      # Install and test
      - name: Install dependencies & run tests
        run: |
          cd app/hello-world-node
          npm install
          npm audit --audit-level high
          npm test

  # Build and push - only on main branch
  build-and-push:
    runs-on: ubuntu-latest
    needs: [detect-changes, security-and-tests]
    if: |
      github.ref == 'refs/heads/main' && 
      needs.detect-changes.outputs.app == 'true' &&
      needs.security-and-tests.result == 'success'
    outputs:
      image_uri: ${{ steps.build.outputs.image_uri }}
    steps:
      - uses: actions/checkout@v4
      
      # AWS Authentication
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      # ECR Login
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      # Build and push Docker image
      - name: Build & push Docker image
        id: build
        run: |
          cd app/hello-world-node
          
          # Build image
          docker build -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }} .
          
          # Push image
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
          
          echo "image_uri=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}" >> $GITHUB_OUTPUT

      # Container security scan
      - name: Security scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.build.outputs.image_uri }}
          format: sarif
          output: trivy-results.sarif

  # Kubernetes validation - only for k8s changes
  validate-k8s:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.k8s == 'true'
    steps:
      - uses: actions/checkout@v4

      # K8s manifest validation
      - name: Validate Kubernetes manifests
        uses: azure/k8s-lint@v3
        with:
          manifests: k8s/
          lintType: kubeconform,dryrun
          kubeconformOpts: -ignore-missing-schemas

  # Update manifests - only on main after successful build
  update-manifest:
    runs-on: ubuntu-latest
    needs: [detect-changes, build-and-push]
    if: |
      github.ref == 'refs/heads/main' &&
      needs.detect-changes.outputs.app == 'true' &&
      needs.build-and-push.result == 'success'
    permissions:
      contents: write  # Allow pushing back to repo
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: false

      # Update manifest - always runs when this job runs
      - name: Update deployment manifest
        run: |
          yq e '.spec.template.spec.containers[0].image = "${{ needs.build-and-push.outputs.image_uri }}"' -i k8s/deployment.yaml
          yq e '.metadata.labels.version = "${{ github.sha }}"' -i k8s/deployment.yaml
          yq e '.spec.template.metadata.labels.version = "${{ github.sha }}"' -i k8s/deployment.yaml

      # Commit changes
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          if git diff --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          
          git add k8s/
          git commit -m "🚀 Update k8s manifests to ${{ github.sha }}"
          git push

  # PR feedback
  pr-checks:
    if: github.event_name == 'pull_request' && always()
    runs-on: ubuntu-latest
    needs: [security-and-tests, validate-k8s]
    steps:
      - name: PR Check Summary
        uses: actions/github-script@v7
        with:
          script: |
            const securityResult = '${{ needs.security-and-tests.result }}';
            const k8sResult = '${{ needs.validate-k8s.result }}';
            
            // Jobs that ran need to succeed, skipped jobs are OK
            const securityOk = securityResult === 'skipped' || securityResult === 'success';
            const k8sOk = k8sResult === 'skipped' || k8sResult === 'success';
            
            const status = securityOk && k8sOk 
              ? '✅ All checks passed! Ready to merge.'
              : '❌ Some checks failed. Please review.';
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## Pull Request Validation Results\n\n${status}`
            });


  # Completion notification
  notify-success:
    runs-on: ubuntu-latest
    needs: [update-manifest]
    if: success() && github.ref == 'refs/heads/main'
    steps:
      - name: Success notification
        run: |
          echo "✅ CI/CD pipeline completed successfully!"
          echo "🔄 ArgoCD will sync the latest changes automatically"